Algoritmo "semnome"

Var
time:caracter

Inicio
escreval("Digite o nome e um time:")
leia(time)

escolha time

caso "São Paulo","Palmeiras","Corinthians"
escreval("Seu time é paulista")

caso "Flamengo","Vasco","Botafogo"
escreval("Seu time é carioca")

caso "Grêmio","Cruzeiro","Inter"
escreval("Seu time é Sulista")

outrocaso
   escreval("Time invalido")

fimescolha


fimalgoritmo